// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfdmfaznsoghazcigluw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZG1mYXpuc29naGF6Y2lnbHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4MjAyMTEsImV4cCI6MjA4MDM5NjIxMX0.dL4iGWIdtpRWf27nE37jPaAJ_HUycoTfpVcWiy0OSZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
